"""empty message

Revision ID: 632c04c824f9
Revises: 1c013f33c546
Create Date: 2024-10-20 18:14:52.689732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632c04c824f9'
down_revision = '1c013f33c546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
